### ISSUE TITLE
DeepLinking to Apps which are not Installed yet?

### ISSUE THREAD

**Issue by confile** [vimeo/VIMDeeplink#2]
Is it possible to DeepLink to Apps which are not Installed yet?

**Comment by alfiehanssen** [comment]
@confile, 

When the app is not installed the best you can do (at least to my knowledge) is re-direct the user to the download page for the app in the App Store:

`let success = VIMDeeplink.viewVimeoAppInAppStore()`

Make sense?

**Comment by confile** [comment]
I did not get it could you please be more specific?

**Comment by alfiehanssen** [comment]
You cannot deeplink into an app that is not installed on the device. 

As an alternative, you can open the app's App Store page in mobile Safari. Do this by calling this method:

`let success = VIMDeeplink.viewVimeoAppInAppStore()`

This method will open this URL in mobile Safari: 

`itms-apps://itunes.apple.com/us/app/425194759`

You could also just use that URL directly.
