### ISSUE TITLE
Doesn't support channels or groups.

### ISSUE THREAD

**Issue by timonus** [vimeo/VIMDeeplink#3]
I would love it if this supported opening Vimeo channels or groups within the iOS app. Even if VIMDeeplink didn't support it, it would be cool if it was documented :)

**Comment by alfiehanssen** [comment]
Hey @tijoinc, we'll be adding a number of additional deeplinks to this repo / the iOS app and the README here over the coming weeks / months. Stay tuned. Pretty sure channels will be supported.

**Comment by tijoinc** [comment]
Wonderful, will add to the existing Vimeo integration in [Opener](http://www.opener.link) once you've finished it :smile:

**Comment by alfiehanssen** [comment]
@timonus We recently added a number of new deeplinks. Including channels and categories. No groups though. Check out the `revisions` branch and PR soon to be merged to master.

**Comment by timonus** [comment]
Thanks!
