### ISSUE TITLE
Deep Link to play a video

### ISSUE THREAD

**Issue by bhickey777** [vimeo/VIMDeeplink#6]
When I attempted to play a video after installing the application, the deep link just launches the application put does navigate to the video. Here is my deep link, vimeo://app.vimeo.com/133862388.
Is this the proper format? Thx ahead of time.

**Comment by alfiehanssen** [comment]
Hey @bhickey777 it looks like your link is the wrong format

Check the README, you'll see that you need to append the video URI to the base URL here, yielding: 

`vimeo://app.vimeo.com/videos/133862388`
